### ISSUE TITLE
奇怪的问题增加了

### ISSUE THREAD

**Issue by 8852690** [xfdown/xiaofei-plugin#1]
![image](https://github.com/xfdown/xiaofei-plugin/assets/59615518/c37de813-d2ab-40f2-9ece-2f4d996d6392)
![}8{DQ DFV}4T9E`TYHZ~8TA_tmb](https://github.com/xfdown/xiaofei-plugin/assets/59615518/8fa4f936-4807-4051-b3d7-0c0e9c208d17)
![image](https://github.com/xfdown/xiaofei-plugin/assets/59615518/632bf2b5-e139-45f6-ae55-b99fb98c2b76)
戳一戳功能是开启的，但是戳了不响应，喵喵和其他带戳一戳的我也全关了。然后就是“#来首歌”响应了，但并没有实际返回，而是直接写完成。。。

**Comment by xfdown** [comment]
哦，忘记推，现在好了，你更新一下。

**Comment by xfdown** [comment]
。

**Comment by xfdown** [comment]
。
